### PR TITLE
修复些文档中的小瑕疵

### PR DESCRIPTION
**Pull request by anine09**

### CODE REVIEW

**Comment by ChuanyuXue** [comment]
Thank you for the contribution. I would highly recommend you integrate `student.py ` into the Chapter 3 before the merge. Thanks.

**Comment by anine09** [comment]
Well, about this question, I explained this in Chapter 4.
“注意！经过新一轮校对后，我们修改了 student 类的代码，下图代码已经废弃，我们同时在GitHub中提供 student.py 文件供大家参考”

**Comment by anine09** [comment]
> Well, about this question, I explained this in Chapter 4. “注意！经过新一轮校对后，我们修改了 student 类的代码，下图代码已经废弃，我们同时在GitHub中提供 student.py 文件供大家参考”

I don't think it's easy for beginners to understand Python modules, so I want to make this easier.

**Comment by ChuanyuXue** [comment]
> > Well, about this question, I explained this in Chapter 4. “注意！经过新一轮校对后，我们修改了 student 类的代码，下图代码已经废弃，我们同时在GitHub中提供 student.py 文件供大家参考”
> 
> I don't think it's easy for beginners to understand Python modules, so I want to make this easier.

I do agree this code modification is going to be more helpful to beginners and easier to understand. Personally, I feel adding a `student.py` impedes the integrity of this tutorial, as I want each ipynb file as a Chapter like a book. I have just replaced the picture of your modified `student.py` in the `/src` directory as `fig44.png` and maybe you want to remove this comment in Chapter4 :)

**Comment by anine09** [comment]
But it can not solve `No module named 'student'`.

**Comment by anine09** [comment]
But it can not solve `No module named 'student'`.

ModuleError

So I have two solutions to this problem. 
1. Move `student.py` to `/src`, then `import src.student`. The project structure will not be broken. **But I think we need to explain `src.student` briefly.**
2. Add a code cell to generate `student.py` in `/`, then `import student`. in this case, when beginners running the notebook, they can easier to `import student`. **But the project structure will be broken after running code cell locally.**

So how do you think?

**Comment by ChuanyuXue** [comment]
In my perspective, I would prefer the second option as this file is only created when the user needs it in Chapter 4.

But I believe we also want to explain why do we add this code cell in the ipynb file.

**Pull request closed without merging**
